# version: {build}
branches:
  # whitelist
  only:
    - master

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

image:
- Visual Studio 2015
- Visual Studio 2017

before_build:
  - nuget restore

build: msbuild CloverQ.sln
